language: android
jdk: oraclejdk8
sudo: required
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - ANDROID_API=28
  - EMULATOR_API_LEVEL=21
  - ANDROID_BUILD_TOOLS=29.0.2
  - ADB_INSTALL_TIMEOUT=8
  - secure: a/likxg6BNql6VDWlwJyzzJml79yb9guRSK41EGbKFXgNMVBKQfNUgH2DzD3hYACczs8iSsactzWHjpZl1FGVivU87Zfy7I0989CaK6UoBlDVU60RTNdbL8B2xcKpAK4Iq4Wg6tt1FTdxj0ULqkH9hPPwBJhbC3joBJ/0eum0jHCPQe8QN9ZsuNgQVVmV+FSbkIYo+ET8v7gIj8Dbq13HOhTJ7Ou/4xoWcEBEDroEG7vNeJF4ymnx4G+3gT7UylP4VGu5czvyCjYoOSLgxOLPpLxM3E5n1vUrz09h8TVOdbcNezrkEadV8QfTNgHRQudML4QgsZdI8HaSJDB5gHf/fATPnD26jK9Yrp43Hx/c2TxCgo+H80+WeW360bHmIhTbbodHf+btuTn8+PzghJp//P8pZEulrOmbSYgjBkL0SIYd3gBkA1o32+p8xmv6ncIrGnbneDFC+OXaxaxmaTjzEhQEbFXFm/VCj2r+/2LqYbFeFlqhlEY1D63/xXwDoIb+iRMjkJQv2nHwaD5jDNFgnHRU9q7wio+FNKmrguDbpmjlbH2WQHWZa4U2MRVrV7V6+VdZ2Wxzv9cSeTsikN3sxbOZ3776CXwcDF8BpYBO9fgas3BhmiOnJnb4DrBRtyZDoAOW3WMBkXr2Ac93EUN1SIqHv+NtdPk6ybmmPs6RCw=
  - secure: UNOr1Msm4oOQs2oqshAGvoDZd9HwLvrjaz1Z4XcL9nmXRe80YE6kxWct3cIFa3cCioi03U1OgsE61RokCxyJRKf7yrnlJ4ATwdVLYRh+JoWfUMOj1Z8xat+srY9nrtVRyuKEEGqa/wIs0qYVn7xY4UBQEQaKUvC76vRWEIEyTdbrgz2sSVCRBPDcmJuWp0GDgcX/sbBC6DxUbZZhlhVk+dJk6BhoS3H+c1ndaGmQDKEmfYWccMs7vtpUzvLYSV6rVdW9okWmnxUVFrg5w44OM1d6TYWN150dG3cPJHNIr80Pv/IQkjsQ+eA0Bnzv2gArE0PW9iPur8/dZuqbhlalcM08b1OAPIHQ8GY2NlKDxFvOi/utJBsM6pRY+mR81EfvDh1DFWCLnuo9IILKZ8VgxMqf6XXVhCgvMus+UKzSwu2spgrwhIdS3aFZPZUfe7YxyGXaI/Jpq5529e/zkQdusdqCzXwSzwUO2r3XiLU+mxAOMSTwAtQfTwNDBpCf+u+Oey+Q+T/d4xqDDWprZSGUgH/pceQqY7Ox5PeFOoLBIXGI20aNlrgaeVvCuGd/HF/3AqcBp38KDs9hOTQ/MmUv2xoFg8Kv8XW45JCPcyeIfNWxvnqAeQRJB8t2erOP1REfD099m4DJzWywNg2PxExKE78j63oelAer70DwPRccJvQ=
android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - android-$EMULATOR_API_LEVEL
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support
  - addon-google_apis-google-19
  - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
  - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
- openssl aes-256-cbc -K $encrypted_4b85434bbf5d_key -iv $encrypted_4b85434bbf5d_iv
  -in AlcoDiary.jks.enc -out AlcoDiary.jks -d
- chmod +x ./gradlew
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- "./gradlew dependencies || true"
before_script:
- echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a -c
  32M
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- sleep 60
- adb devices
- adb shell input keyevent 82 &
script:
- "./gradlew clean build assembleRelease"
before_deploy:
- cp $TRAVIS_BUILD_DIR/AlcoDiary.jks $HOME
- cd app/build/outputs/apk/release/
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/AlcoDiary.jks
  -storepass $storepass -keypass $keypass app-release-unsigned.apk alcodiarykey
- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS}/zipalign -v 4 app-release-unsigned.apk
  alcodiary.apk"
deploy:
  provider: releases
  api_key:
    secure: Cx2mXF5yL3Qi4M6oMi0WIjxZXYE9Eq8DglYEPY+Y8nlzOHV7dndJnsJpkgWyEXv0EmGL+Ha0Rgy5IbNIZuJIaew88oejV6t+SCPeWwttQWQutTvqLcz0jUfWg4yr8azQbYmXeOrbdDCnSYNxTE/EEAUUx62brxfXfdOhsQ3udrq1IbZsdUTLtnvDg6K/niqh0lcstVW6eGgnLFJ88tQo/+0bnRrXP5SNUHcsICXGF/8pdrwObLEsOWXgPN5PnuqvLacxbsyoRZfXT/O8JVQNeU6Z6YxmVS789DB9aUmvdIwo25JHVM25TNQOOqIUrit/JUlPI0amDS2i9Asnp/Hqy8s/lfjxmRN2rEvLymCZ/Oj9t666fe7fxfZZ75xvFnE64QjYEuzrabL3KxePqxt0RsEYpoIYe3Clk9t4KSdKt8iHGllsaYxYi9YiMow+Oz+P7e+GWJ2jmw1e6oZWFnOBfylougwr8gjD9Hu+V/x4aT3o+/aVO8tMEIopfeY/2xaTJEeZeE6zdmw0zGPQ0J8Sr6RutPGMcnxe0gOQwlK14giRe9sZ+JAp8Ne/2NQ72GvoF106Co3YSlUy2sCaNdD6azN1RFab0uYHjZPTC504QIqRqEJSOgZUQILn/66/oewmeaJs96imGaqg//lpfW8YwWAM87+bGgf0M38DUmKgmTE=
  file: 'alcodiary.apk'
  on:
    repo: Kapibarabanka/AlcoDiary
    tags: true
    jdk: oraclejdk8
  skip_cleanup: 'true'
